-- Sugestões enviadas pelos usuários (botão flutuante).
CREATE TABLE IF NOT EXISTS public.user_suggestions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
  user_name text,
  user_email text,
  user_role text,
  message text NOT NULL,
  page_tab text,
  page_label text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_suggestions_created_at_idx
  ON public.user_suggestions (created_at DESC);

CREATE INDEX IF NOT EXISTS user_suggestions_user_id_idx
  ON public.user_suggestions (user_id);
